### ISSUE TITLE
google-related

### ISSUE THREAD

**Issue by 0xmountaintop** [SebastianElvis/sharding-bib#1]
+ BigTable (already included)
+ The Google File System: https://static.googleusercontent.com/media/research.google.com/en//archive/gfs-sosp2003.pdf
+ MapReduce: simplified data processing on large clusters

**Comment by SebastianElvis** [comment]
The GFS paper and the MapReduce paper have nothing to do with sharding.

- GFS
First, GFS is a file system rather than a database system. The design rationale of  distributed file systems is completely different with distributed database. For example, the data structure used (node/block in fs while index in db), the fault tolerance (db usually needs no data redundancy for tolerating data loss as the underlying fs guarantees that), and so on...
Second, DB/Blockchain usually run over reliable file systems. They focus on different aspects of reliability. DB/Blockchain cares for reliable consensus protocols while FS cares for reliable storage.

- MapReduce
The Google's MapReduce paper basically provides a way to implement the conventional MapReduce functionalities over GFS. MapReduce is a pattern of running general-purpose computations on distributed (sharded or replicated) systems. Still, such focus (computation) is different from papers in this list (secure and fault-tolerant sharding with consensus).

**Comment by 0xmountaintop** [comment]
thx for ur explanation
